export const DATABASE_ID = process.env.NOTION_DATABASE_ID
export const TOKEN = process.env.NOTION_TOKEN
export const NOTION_TESTIMONIALS_DATABASE_ID = process.env.NOTION_TESTIMONIALS_DATABASE_ID
export const NOTION_PERSONAL_PROJECTS_DATABASE_ID = process.env.NOTION_PERSONAL_PROJECTS_DATABASE_ID