import React from 'react'
import Head from 'next/head'
import Hero from '../components/hero'
import Carousel from '../components/carousel/index.js'
import {TOKEN, NOTION_TESTIMONIALS_DATABASE_ID} from '../config/index.js'

export default function Home({result}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <section>
        <Carousel carouselData={result} />
      </section>
    </>
  )
}

export async function getStaticProps() {
  const options = {
    method: 'POST',
    headers: {
      accept: 'application/json',
      'Notion-Version': '2022-06-28',
      'content-type': 'application/json',
      Authorization: `Bearer ${TOKEN}`
    }
  };

  const res = await fetch(`https://api.notion.com/v1/databases/${NOTION_TESTIMONIALS_DATABASE_ID}/query`, options)

  const data = await res.json()
  const result = JSON.stringify(data.results)
  return {
    props: {result}, // will be passed to the page component as props
  }
}
